drone_id: MyVehicle
frame_id: base_link
simulated: true

flight_controller:
  type: ardupilot
  fcu_url: udp://127.0.0.1:14551@

sensors:
  camera_front:
    type: webcam
    topic: /camera_front/image_raw
    frame: camera_front
    position: [0.0508, 0.0, 0.018]
    orientation_rpy: [0.0, 0.0, 0.0]
