drone_id: ecco_001
frame_id: base_link
simulated: false

flight_controller:
  type: px4
  fcu_url: udp://127.0.0.1:14575@

sensors:
  camera_front:
    type: mapir_rgn
    topic: /mapir_rgn/image_raw
    frame: mapir_rgn
    stream: camera1
    position: [0.094, 0.021, .057]
    orientation_rpy: [0.0, 0.0, 0.0]

