global_frame: slam_map
robot_base_frame: base_link
max_obstacle_height: 10.0  # assume something like an arm is mounted on top of the robot

# Obstacle Cost Shaping (http://wiki.ros.org/costmap_2d/hydro/inflation)
robot_radius: 0.50  # distance a circular robot should be clear of the obstacle (kobuki: 0.18)
# footprint: [[x0, y0], [x1, y1], ... [xn, yn]]  # if the robot is not circular

map_type: voxel
width: 100
height: 100
resolution: 1.0
update_frequency: 1.0
publish_frequency: 1.0
origin_x: -50.0
origin_y: -50.0
track_unknown_space:  true    #true needed for disabling global path planning through unknown space
rolling_window: true
transform_tolerance: 0.25

obstacle_layer:
  enabled:              true
  max_obstacle_height:  10.0
  origin_z:             0.0
  z_resolution:         0.2
  z_voxels:             100
  unknown_threshold:    15
  mark_threshold:       0
  combination_method:   1
  track_unknown_space:  true    #true needed for disabling global path planning through unknown space
  obstacle_range: 200
  raytrace_range: 200.0
  publish_voxel_map: false
  observation_sources:  slam_pcl
  slam_pcl:
    data_type: PointCloud2
    topic: cloud_registered
    marking: true
    clearing: true
    min_obstacle_height: 1.0
    max_obstacle_height: 2.5
  # for debugging only, let's you see the entire voxel grid

#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation_layer:
  enabled:              true
  cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.5  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
