global_frame: map
robot_base_frame: base_link
max_obstacle_height: 10.0 

robot_radius: 0.50  # distance a circular robot should be clear of the obstacle (kobuki: 0.18)
# footprint: [[x0, y0], [x1, y1], ... [xn, yn]]  # if the robot is not circular

width: 1000
height: 1000
resolution: 1.0
update_frequency: 1.0
publish_frequency: 1.0
origin_x: -500.0
origin_y: -500.0
track_unknown_space:  true    #true needed for frontier finding
rolling_window: true
transform_tolerance: 0.25
raytrace_range: 40.0

plugins: 
    - {name: clear_layer,         type: "clear_layer::ClearLayer"}
    - {name: aerial_layer,        type: "aerial_layer::AerialLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}

#clearing layer marks free space in 2D even without a LiDAR return
clear_layer:
  enabled:              true
  max_obstacle_height:  10.0
  combination_method:   1
  track_unknown_space:  true    #true needed for frontier finding
  obstacle_range: 100
  publish_voxel_map: false
  observation_sources:  slam_pcl
  slam_pcl:
    data_type: PointCloud2
    topic: cloud_registered_map
    marking: true
    clearing: true
    min_obstacle_height: 1.0
    max_obstacle_height: 10.0

#aerial layer can accept map-registered pointclouds 
aerial_layer:
  sensor_frame:         livox_frame
  enabled:              true
  max_obstacle_height:  10.0
  origin_z:             0.0
  z_resolution:         0.5
  z_voxels:             16
  unknown_threshold:    15
  mark_threshold:       0
  combination_method:   1
  track_unknown_space:  true    #true needed for frontier finding
  obstacle_range: 100
  publish_voxel_map: false
  observation_sources:  slam_pcl
  slam_pcl:
    data_type: PointCloud2
    topic: cloud_registered
    marking: true
    clearing: true
    min_obstacle_height: 1.0
    max_obstacle_height: 10.0

#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation_layer:
  enabled:              true
  cost_scaling_factor:  1.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     2.0  # max. distance from an obstacle at which costs are incurred for planning paths.