global_frame: map
robot_base_frame: base_link
max_obstacle_height: 10.0 

robot_radius: 0.50  # distance a circular robot should be clear of the obstacle (kobuki: 0.18)
# footprint: [[x0, y0], [x1, y1], ... [xn, yn]]  # if the robot is not circular

width: 1000
height: 1000
resolution: 1.0
update_frequency: 1.0
publish_frequency: 1.0
origin_x: -500.0
origin_y: -500.0
track_unknown_space:  true    #true needed for frontier finding
rolling_window: true
transform_tolerance: 0.25
obstacle_range: 40.0
raytrace_range: 40.0

plugins: 
    - {name: aerial_layer,        type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
    
#aerial layer can accept map-registered pointclouds 
aerial_layer:
  enabled:              true
  max_obstacle_height:  10.0
  origin_z:             0.0
  z_resolution:         0.5
  z_voxels:             16
  unknown_threshold:    15
  mark_threshold:       1
  combination_method:   1
  track_unknown_space:  true    #true needed for frontier finding
  publish_voxel_map: false
  observation_sources:  slam_pcl
  slam_pcl:
    data_type: PointCloud2
    topic: cloud_registered_body
    marking: true
    clearing: true
    min_obstacle_height: 1.0
    max_obstacle_height: 10.0

#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation_layer:
  enabled:              true
  cost_scaling_factor:  1.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     2.0  # max. distance from an obstacle at which costs are incurred for planning paths.

