image_width: 1920
image_height: 1080
camera_name: immervision
camera_matrix:
  rows: 3
  cols: 3
  data: [700.7235107421875, 0.0, 1308.0,
         0.0, 700.7235107421875, 982.0,
         0.0, 0.0, 1.0]
distortion_model: fisheye
distortion_coefficients:
  rows: 1
  cols: 4
  data: [0.02677028626203537, -0.08014970272779465, 0.02631326392292976, -0.003371678292751312]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.000000, 0.000000, 0.000000,
         0.000000, 1.000000, 0.000000,
         0.000000, 0.000000, 1.000000]
projection_matrix:
  rows: 3
  cols: 4
  data: [700.7235107421875, 0.0, 1308.0, 0.0,
         0.0, 700.7235107421875, 982.0, 0.0,
         0.0, 0.0, 1.0, 0.0]