image_width: 1920
image_height: 1080
camera_name: immervision
camera_matrix:
  rows: 3
  cols: 3
  data: [531.217819, -9.803565, 636.092748,
         0.000000, 546.333248, 364.235079,
         0.000000, 0.000000, 1.000000]
distortion_model: fisheye
distortion_coefficients:
  rows: 1
  cols: 4
  data: [0.354302, -2.560501, 0.019287, -94.292276]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.000000, 0.000000, 0.000000,
         0.000000, 1.000000, 0.000000,
         0.000000, 0.000000, 1.000000]
projection_matrix:
  rows: 3
  cols: 4
  data: [531.217819, -9.803565, 636.092748, 0.000000,
         0.000000, 546.333248, 364.235079, 0.000000,
         0.000000, 0.000000, 1.000000, 0.000000]
