/**:
    ros__parameters:
      video_device: "/dev/video4"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "see3cam"
      pixel_format: "uyvy"  # see usb_cam/supported_formats for list of supported formats. for see3cam, alt mono8 or mono16
      av_device_format: "RGB24"
      image_width: 1280
      image_height: 720
      camera_name: "see3cam"
      camera_info_url: "package://vehicle_launch/config/see3cam_info.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: true
      white_balance: 4000
      autoexposure: true
      exposure: 100
      autofocus: false
      focus: -1